#!/bin/bash
# Copyright (c) 2026 Cornelis Networks. All rights reserved.

# cuda_lt.sh — Wrapper to compile .cu files into libtool .lo objects
#
# Libtool requires .lo (libtool object) files to properly link objects
# into shared libraries. nvcc produces raw .o files which libtool silently
# drops when merging convenience libraries. This script wraps nvcc to
# produce both PIC and non-PIC .o files, then writes the .lo metadata
# file that libtool expects.
#
# Based on the pattern used by openucx/ucc (NVIDIA's Unified Collective
# Communication library).
#
# Usage: cuda_lt.sh "$(LIBTOOL)" output.lo $(NVCC) -c input.cu [flags...]

set -e

libtool_file=$1
lo_filepath=$2

# Derive .o path from .lo path
o_filepath="${lo_filepath%.lo}.o"
lo_dir=$(dirname "$o_filepath")
o_filename=$(basename "$o_filepath")

# Libtool convention: PIC objects go in .libs/, non-PIC in current dir
local_pic_dir=".libs/"
local_npic_dir=""
pic_dir="${lo_dir}/${local_pic_dir}"
npic_dir="${lo_dir}/${local_npic_dir}"

pic_filepath="${pic_dir}${o_filename}"
npic_filepath="${npic_dir}${o_filename}"
local_pic_filepath="${local_pic_dir}${o_filename}"
local_npic_filepath="${local_npic_dir}${o_filename}"

mkdir -p "$pic_dir"

# Build PIC version (for shared library) — nvcc uses -Xcompiler for host flags
cmd="${@:3} -Xcompiler -fPIC -o ${pic_filepath}"
echo "$cmd"
$cmd

# Build non-PIC version (for static library)
cmd="${@:3} -o ${npic_filepath}"
echo "$cmd"
$cmd

# Write the .lo metadata file that libtool expects
libtool_version="$(${libtool_file} --version | head -1 | sed 's/^/#/g')"

cat > "${lo_filepath}" <<LOEOF
# ${lo_filepath} - a libtool object file
# Generated by cuda_lt.sh for nvcc/libtool integration
# ${libtool_version}

# Please DO NOT delete this file!
# It is necessary for linking the library.

# Name of the PIC object.
pic_object='${local_pic_filepath}'

# Name of the non-PIC object.
non_pic_object='${local_npic_filepath}'
LOEOF
